services:
  app:
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      GITHUB_ORG: ${GITHUB_ORG:-}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  proxy:
    image: nginx:1.28.0
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
